# Generated by Django 4.2.6 on 2023-10-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
